### ISSUE TITLE
If the table contains `|`, it will not be formatted well

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [takumisoft68/vscode-markdown-table#32]
# If the table contains `|`, it will not be formatted well

When formatting a table containing `|` using `markdowntable.format` (`markdowntable.nextCell` or `markdowntable.prevCell`) as shown below gives the following results:

> Before format

```markdown
|contents|description |
| :---: | :--- |
| If the table contains `|` | it will not be formatted well |
```

> Result (After format)

```markdown
|        contents         | description |
| :---------------------: | :---------- |
| If the table contains ` | `           | it will not be formatted well
```

I expect the following results:

> Expected result

```markdown
|         contents          | description                   |
| :-----------------------: | :---------------------------- |
| If the table contains `|` | it will not be formatted well |
```

It's a easy-to-use extension and it's very helpful.
Thank you.

**Comment by lunelson** [comment]
@takumisoft68 I love this extension, but I am running in to this problem too. 

Would you consider allowing `\|` as a way of escaping the pipe character, so that it can be allowed as cell content?

**Comment by lunelson** [comment]
Alternately, using the `&#124;` HTML entity works

**Comment by takumisoft68** [comment]
@Yarakashi-Kikohshi, @lunelson 

I allowed inline-code and escaping `|` in table, in v0.7.1.
And I released it on 5 Dec 2020.
Try using it!

**Comment by lunelson** [comment]
I'm so glad to hear that @Yarakashi-Kikohshi ! This will certainly make things easier, not to have to remember the HTML entity code for it 😄 

It seems to work great, with one exception: keyboard tabbing through cells still gets caught on the escaped character:

![CleanShot 2021-12-05 at 16 11 19](https://user-images.githubusercontent.com/1242864/144752312-c1ebec22-e732-442d-a9ce-6835dba80ca1.gif)

**Comment by Yarakashi-Kikohshi** [comment]
Thank you for supporting this issue!:smile:

However, as already mentioned by lunelson, keyboard tabbing through cells still gets caught on inline-code too...

**Comment by takumisoft68** [comment]
@lunelson @Yarakashi-Kikohshi 
This is fixed at #34, and v0.7.2 has been released.

**Comment by Yarakashi-Kikohshi** [comment]
With v0.7.2, I can do what I expected!
Thank you for your support. :relaxed:
